// 按需导入
import Vue from 'vue'
import { Dialog, ActionSheet, Search, Button, Switch, Rate, Tabbar, TabbarItem, NavBar, Toast, Swipe, Grid, GridItem, SwipeItem, Icon, Checkbox, Lazyload, Tabs, Tab } from 'vant'
Vue.use(Tabs)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Rate)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(SwipeItem)
Vue.use(Icon)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Lazyload)
Vue.use(Tab)
